# Generated by Django 5.2.1 on 2025-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availableFrom', models.DateField()),
                ('availableTo', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('outdoor', 'Outdoor Activities'), ('transfer', 'Transfer Services'), ('taxi', 'Taxi Services'), ('travelmoney', 'Travel Money'), ('parking', 'Parking Services')], default='', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('minTravelers', models.IntegerField(default=1)),
                ('maxTravelers', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
