# Generated by Django 5.2.1 on 2025-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='type',
            field=models.CharField(choices=[('activities', 'Activities'), ('transfer', 'Airport Transfer'), ('taxi', 'Taxi Services'), ('airporthotel', 'Airport Hotel'), ('parking', 'Parking Services'), ('insurance', 'Travel Insurance'), ('car', 'Car Hire'), ('fasttrack', 'Airport Fast Track'), ('lounge', 'Airport Lounge')], default='', max_length=50),
        ),
    ]
