# Generated by Django 5.2.1 on 2025-05-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_activitytype_holidaypersonalitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaypersonalitytype',
            old_name='name',
            new_name='slug',
        ),
    ]
