from django.core.management.base import BaseCommand
from datetime import date
from theApp.models import addOn

class Command(BaseCommand):
    def handle(self, *args, **options):
        sample_data = [
            {
                "name": "City Walking Tour",
                "description": "A guided walking tour through the city's historic landmarks.",
                "price": 29.99,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "activities",
                "location": "London",
                "minTravelers": 1,
                "maxTravelers": 10,
                "url": "https://example.com/walking-tour"
            },
            {
                "name": "Airport to Hotel Transfer",
                "description": "Private car transfer from the airport to your hotel.",
                "price": 45.00,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "transfer",
                "location": "Manchester",
                "minTravelers": 1,
                "maxTravelers": 4,
                "url": "https://example.com/airport-transfer"
            },
            {
                "name": "Travel Insurance Plan A",
                "description": "Comprehensive travel insurance for your trip.",
                "price": 18.50,
                "availableFrom": date(2025, 5, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "insurance",
                "location": "",
                "minTravelers": 1,
                "maxTravelers": 10,
                "url": "https://example.com/insurance-a"
            },
            {
                "name": "Festival Entry Ticket",
                "description": "Entry ticket to the annual summer music festival.",
                "price": 55.00,
                "availableFrom": date(2025, 6, 10),
                "availableTo": date(2025, 6, 20),
                "active": True,
                "type": "activities",
                "location": "Leeds",
                "minTravelers": 1,
                "maxTravelers": 5,
                "url": "https://example.com/festival-ticket"
            },
            {
                "name": "Taxi from Station",
                "description": "Book a local taxi from the train station to your accommodation.",
                "price": 20.00,
                "availableFrom": date(2025, 5, 15),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "taxi",
                "location": "Liverpool",
                "minTravelers": 1,
                "maxTravelers": 4,
                "url": "https://example.com/taxi-station"
            },
            {
                "name": "Currency Exchange Voucher",
                "description": "Special rates for exchanging your currency.",
                "price": 0.00,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 9, 1),
                "active": True,
                "type": "travelmoney",
                "location": "Glasgow",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/exchange"
            },
            {
                "name": "Airport Parking Space",
                "description": "Secure airport parking for the duration of your trip.",
                "price": 75.00,
                "availableFrom": date(2025, 5, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "parking",
                "location": "Birmingham",
                "minTravelers": 1,
                "maxTravelers": 1,
                "url": "https://example.com/parking"
            },
            {
                "name": "Car Hire – Compact",
                "description": "Rent a compact car for your travel.",
                "price": 120.00,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "car",
                "location": "London",
                "minTravelers": 1,
                "maxTravelers": 4,
                "url": "https://example.com/compact-car"
            },
            {
                "name": "Airport Lounge Access",
                "description": "Relax in the airport lounge before your flight.",
                "price": 35.00,
                "availableFrom": date(2025, 5, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "lounge",
                "location": "Heathrow",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/lounge-access"
            },
            {
                "name": "Fast Track Security Pass",
                "description": "Skip the security queues at the airport.",
                "price": 12.00,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "fasttrack",
                "location": "Gatwick",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/fasttrack"
            },
            {
                "name": "Zipline Adventure",
                "description": "Experience the thrill of ziplining over scenic landscapes.",
                "price": 50.00,
                "availableFrom": date(2025, 7, 1),
                "availableTo": date(2025, 9, 30),
                "active": True,
                "type": "activities",
                "location": "Lake District",
                "minTravelers": 1,
                "maxTravelers": 5,
                "url": "https://example.com/zipline"
            },
            {
                "name": "Scuba Diving Experience",
                "description": "Explore underwater life with guided scuba diving.",
                "price": 95.00,
                "availableFrom": date(2025, 6, 1),
                "availableTo": date(2025, 8, 31),
                "active": True,
                "type": "activities",
                "location": "Cornwall",
                "minTravelers": 2,
                "maxTravelers": 6,
                "url": "https://example.com/scuba"
            },
            {
                "name": "Evening River Cruise",
                "description": "Enjoy dinner and views on a riverboat.",
                "price": 65.00,
                "availableFrom": date(2025, 5, 10),
                "availableTo": date(2025, 9, 10),
                "active": True,
                "type": "activities",
                "location": "York",
                "minTravelers": 1,
                "maxTravelers": 8,
                "url": "https://example.com/river-cruise"
            },
            {
                "name": "Weekend Festival Pass",
                "description": "Access to all events over the weekend festival.",
                "price": 120.00,
                "availableFrom": date(2025, 6, 20),
                "availableTo": date(2025, 6, 22),
                "active": True,
                "type": "activities",
                "location": "Brighton",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/festival-pass"
            },
            {
                "name": "Theatre Show Ticket",
                "description": "Front-row seats to a West End performance.",
                "price": 89.99,
                "availableFrom": date(2025, 5, 1),
                "availableTo": date(2025, 12, 1),
                "active": True,
                "type": "activities",
                "location": "London",
                "minTravelers": 1,
                "maxTravelers": 2,
                "url": "https://example.com/theatre"
            },
            {
                "name": "Snowdonia Hiking Guide",
                "description": "Guided hike across Snowdonia National Park.",
                "price": 40.00,
                "availableFrom": date(2025, 6, 15),
                "availableTo": date(2025, 9, 15),
                "active": True,
                "type": "activities",
                "location": "Wales",
                "minTravelers": 2,
                "maxTravelers": 10,
                "url": "https://example.com/hiking"
            },
            {
                "name": "Kayaking Session",
                "description": "1-hour guided kayaking on calm waters.",
                "price": 35.00,
                "availableFrom": date(2025, 7, 1),
                "availableTo": date(2025, 9, 30),
                "active": True,
                "type": "activities",
                "location": "Bath",
                "minTravelers": 1,
                "maxTravelers": 4,
                "url": "https://example.com/kayaking"
            },
            {
                "name": "Cooking Class",
                "description": "Learn to cook authentic local dishes.",
                "price": 70.00,
                "availableFrom": date(2025, 6, 5),
                "availableTo": date(2025, 11, 30),
                "active": True,
                "type": "activities",
                "location": "Oxford",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/cooking"
            },
            {
                "name": "Ghost Tour",
                "description": "A spooky night-time tour of haunted sites.",
                "price": 25.00,
                "availableFrom": date(2025, 10, 1),
                "availableTo": date(2025, 10, 31),
                "active": True,
                "type": "activities",
                "location": "Edinburgh",
                "minTravelers": 1,
                "maxTravelers": 5,
                "url": "https://example.com/ghost-tour"
            },
            {
                "name": "Museum Day Pass",
                "description": "Unlimited entry to multiple museums in the city.",
                "price": 22.00,
                "availableFrom": date(2025, 5, 1),
                "availableTo": date(2025, 12, 31),
                "active": True,
                "type": "activities",
                "location": "Cambridge",
                "minTravelers": 1,
                "maxTravelers": 6,
                "url": "https://example.com/museum-pass"
            }
        ]
        
        for entry in sample_data:
            addOn.objects.create(**entry)
